version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@pulumi/pulumi"
    versions:
    - 2.19.0
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.0
    - 2.23.1
    - 2.23.2
    - 2.24.1
    - 2.25.0
    - 3.0.0
  - dependency-name: "@pulumi/aws"
    versions:
    - 3.25.1
    - 3.26.1
    - 3.27.0
    - 3.28.0
    - 3.28.1
    - 3.29.0
    - 3.29.1
    - 3.30.0
    - 3.30.1
    - 3.31.0
    - 3.32.0
    - 3.32.1
    - 3.32.2
    - 3.33.0
    - 3.34.1
    - 3.34.2
    - 3.35.0
    - 3.36.0
    - 3.37.0
    - 3.38.0
    - 3.38.1
    - 4.0.0
  - dependency-name: "@pulumi/eks"
    versions:
    - 0.22.0
    - 0.23.0
